### ISSUE TITLE
能否提供一个编译好的安装包

### ISSUE THREAD

**Issue by JunQu** [yuzhengyang/Moana#1]
我是个新手，想用wakatime记录一下学习编程的时间。在CSDN上看到您的文章，所以想尝试一下这个软件，但我不熟悉C#，能麻烦您提供一份编译好的程序吗？可以的话，我会在这个项目找的，也可以直接发给我的邮箱 junjv@outlook.com ，谢谢。

**Comment by yuzhengyang** [comment]
我提交了一份编译后的程序，在 Moana_Publish 文件夹里；

[下载链接](https://github.com/yuzhengyang/Moana/raw/master/Moana_Publish/Moana_1.0.0.0.rar)

**Comment by JunQu** [comment]
非常感谢
